/**
 * Parse Mermaid flowchart/graph syntax back into diagram nodes and edges.
 * This is a best-effort parser for mermaid code generated by diagramToMermaid.
 *
 * @param {string} src - Mermaid source code
 * @returns {{ nodes: Array, edges: Array, direction: string, mode: string }}
 */
export function mermaidToDiagram(src) {
  const lines = src.split('\n').map(l => l.trim()).filter(Boolean);
  const nodes = [];
  const edges = [];
  let direction = 'TD';
  let mode = 'flowchart';

  // Parse header
  const header = lines[0] || '';
  const dirMatch = header.match(/^(?:graph|flowchart)\s+(TD|TB|LR|RL|BT)/i);
  if (dirMatch) direction = dirMatch[1].toUpperCase();

  // Track classDefs for knowledge graph detection
  const classDefs = {};
  const classAssignments = {};

  // Metadata storage for round-trip fidelity
  let metadataMap = null;

  let idCounter = 0;
  const nodeMap = new Map(); // id → node

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];

    // Parse metadata comments: %% meta:nodeId:key=val,key=val
    const metaMatch = line.match(/^%%\s*meta:(\w+):(.+)/);
    if (metaMatch) {
      if (!metadataMap) metadataMap = new Map();
      const metaId = metaMatch[1];
      const metaStr = metaMatch[2];
      const props = {};
      for (const pair of metaStr.split(',')) {
        const eqIdx = pair.indexOf('=');
        if (eqIdx > 0) {
          const k = pair.slice(0, eqIdx).trim();
          const v = pair.slice(eqIdx + 1).trim();
          props[k] = v;
        }
      }
      metadataMap.set(metaId, props);
      continue;
    }

    // Skip other comments
    if (line.startsWith('%%')) continue;

    // Skip classDef lines but record them
    const classDefMatch = line.match(/^classDef\s+(\w+)\s+(.+)/);
    if (classDefMatch) {
      classDefs[classDefMatch[1]] = classDefMatch[2];
      mode = 'knowledge'; // classDef implies knowledge graph
      continue;
    }

    // Skip class assignment lines but record them
    const classMatch = line.match(/^class\s+([\w,]+)\s+(\w+)/);
    if (classMatch) {
      const ids = classMatch[1].split(',');
      for (const id of ids) {
        classAssignments[id.trim()] = classMatch[2];
      }
      continue;
    }

    // Try to parse as edge: nodeA -->|"label"| nodeB  or  nodeA --> nodeB
    // Labeled edge: A -->|"text"| B  or  A -->|text| B
    const labeledEdge = line.match(/^(\w+)\s+(-->|---|-\.->|-\.-)\|"?([^"|]*)"?\|\s*(\w+)/);
    // Unlabeled edge: A --> B
    const simpleEdge = !labeledEdge && line.match(/^(\w+)\s+(-->|---|-\.->|-\.-)\s+(\w+)$/);
    const edgeMatch = labeledEdge || simpleEdge;
    if (edgeMatch) {
      const from = edgeMatch[1];
      const arrow = edgeMatch[2];
      const to = labeledEdge ? edgeMatch[4] : edgeMatch[3];
      const label = labeledEdge ? edgeMatch[3].trim() : '';
      const isLine = arrow === '---' || arrow === '-.-';
      const isDotted = arrow.includes('.');
      edges.push({
        id: 'e' + (++idCounter),
        from,
        to,
        label,
        style: isDotted ? 'dotted' : 'solid',
        edgeType: isLine ? 'line' : 'arrow',
        color: '#1b1b1f',
      });
      // Ensure nodes exist
      ensureNode(from);
      ensureNode(to);
      continue;
    }

    // Try to parse as node definition
    // Rectangle: id["label"]
    const rectMatch = line.match(/^(\w+)\["([^"]*)"\]/);
    if (rectMatch) {
      addOrUpdateNode(rectMatch[1], rectMatch[2], 'rectangle');
      continue;
    }

    // Ellipse: id(("label"))
    const ellipseMatch = line.match(/^(\w+)\(\("([^"]*)"\)\)/);
    if (ellipseMatch) {
      addOrUpdateNode(ellipseMatch[1], ellipseMatch[2], 'ellipse');
      continue;
    }

    // Diamond: id{"label"}
    const diamondMatch = line.match(/^(\w+)\{"([^"]*)"\}/);
    if (diamondMatch) {
      addOrUpdateNode(diamondMatch[1], diamondMatch[2], 'diamond');
      continue;
    }
  }

  function ensureNode(id) {
    if (!nodeMap.has(id)) {
      addOrUpdateNode(id, id, 'rectangle');
    }
  }

  function addOrUpdateNode(id, label, type) {
    if (nodeMap.has(id)) {
      const n = nodeMap.get(id);
      n.label = label;
      n.type = type;
      return;
    }
    // Auto-layout: arrange in a grid
    const idx = nodes.length;
    const cols = direction === 'LR' || direction === 'RL' ? 1 : 3;
    const col = idx % cols;
    const row = Math.floor(idx / cols);
    const spacing = direction === 'LR' ? { x: 200, y: 100 } : { x: 180, y: 120 };
    const startX = 200;
    const startY = 150;

    const w = type === 'diamond' ? 120 : 140;
    const h = type === 'diamond' ? 80 : 60;

    const node = {
      id,
      type,
      x: startX + col * spacing.x,
      y: startY + row * spacing.y,
      w,
      h,
      label,
      color: '#1b1b1f',
    };
    nodes.push(node);
    nodeMap.set(id, node);
  }

  // Apply stored metadata to restore node types, positions, sizes, and colors
  if (metadataMap) {
    for (const node of nodes) {
      const meta = metadataMap.get(node.id);
      if (!meta) continue;
      if (meta.type) node.type = meta.type;
      if (meta.x !== undefined) node.x = parseFloat(meta.x);
      if (meta.y !== undefined) node.y = parseFloat(meta.y);
      if (meta.w !== undefined) node.w = parseFloat(meta.w);
      if (meta.h !== undefined) node.h = parseFloat(meta.h);
      if (meta.color) node.color = meta.color;
    }

    // Build a lookup for connected edge metadata by from+to
    const edgeMetaByFromTo = new Map();
    for (const [id, meta] of metadataMap) {
      if (meta.from && meta.to) {
        edgeMetaByFromTo.set(`${meta.from}->${meta.to}`, meta);
      }
    }

    // Apply metadata to connected edges (restore color, style, edgeType)
    for (const edge of edges) {
      if (edge.standalone) continue;
      const key = `${edge.from}->${edge.to}`;
      const meta = edgeMetaByFromTo.get(key);
      if (!meta) continue;
      if (meta.color) edge.color = meta.color;
      if (meta.style) edge.style = meta.style;
      if (meta.edgeType) edge.edgeType = meta.edgeType;
      if (meta.label) edge.label = meta.label.replace(/&#44;/g, ',');
    }

    // Reconstruct standalone edges from metadata
    for (const [id, meta] of metadataMap) {
      if (meta.standalone === 'true') {
        edges.push({
          id,
          standalone: true,
          x1: parseFloat(meta.x1),
          y1: parseFloat(meta.y1),
          x2: parseFloat(meta.x2),
          y2: parseFloat(meta.y2),
          label: meta.label ? meta.label.replace(/&#44;/g, ',') : '',
          style: meta.style || 'solid',
          color: meta.color || '#1b1b1f',
          edgeType: meta.edgeType || 'arrow',
        });
      }
    }
  }

  return { nodes, edges, direction, mode };
}
